# Generated by Django 5.0.4 on 2024-04-11 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Details', models.CharField(max_length=250)),
                ('Task_Type', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], max_length=50)),
                ('taskDetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.user')),
            ],
        ),
    ]
