# Generated by Django 5.0.4 on 2024-04-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0002_remove_task_taskdetail_user_taskdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='taskDetail',
            field=models.ForeignKey(choices=[('Pending', 'Pending'), ('Done', 'Done')], null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.task'),
        ),
    ]
