# Generated by Django 5.0.4 on 2024-04-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0004_remove_user_taskdetail_user_tasktype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasktype',
        ),
        migrations.AddField(
            model_name='user',
            name='taskdetail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.task'),
        ),
    ]
