# Generated by Django 5.0.4 on 2024-04-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0005_remove_user_tasktype_user_taskdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='taskdetail',
        ),
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.user'),
        ),
    ]
