# Generated by Django 5.0.4 on 2024-04-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0006_remove_user_taskdetail_task_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.user'),
        ),
    ]
