# Generated by Django 5.0.4 on 2024-04-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0007_alter_task_tasktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasktype',
        ),
        migrations.AddField(
            model_name='user',
            name='tasktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.task'),
        ),
    ]
